### ISSUE TITLE
Add ghc-mod-check.sh

### ISSUE THREAD

**Issue by simonyangme** [Hogeyama/dotfiles#1]
Hi, I'm trying to get ghc-mod to work with neovim. Do you mind sharing your ghc-mod-check.sh? It's referenced on this line: https://github.com/Hogeyama/dotfiles/blob/master/init.vim#L147

Thanks!

**Comment by Hogeyama** [comment]
I added it.
The script only helps running `ghc-mod check` out of project root directory.
I hope it can be of any help.

**Comment by simonyangme** [comment]
Thanks! :100:
